###
POST b451dbd8trial-dev-dice.cfapps.us10.hana.ondemand.com/main/Users
Content-Type: application/json

{"Username": "Oriery",
"Bio": "Just a nice guy.",
"DateOfBirth": "2002-10-29",
"Sex": 1,
"Email": "aleksandr.panev.2002@gmail.com",
"PhoneNumber": "+375296191617",
"Salt": "testsalt",
"PassHash": "testhashtesthashtesthashtesthash"
}

###
GET b451dbd8trial-dev-dice.cfapps.us10.hana.ondemand.com/main/Users


###
DELETE http://localhost:4004/main/Users/